name: savewise
description: Application de suivi d'épargne & objectifs financiers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Base de données
  sqflite: ^2.3.0
  path: ^1.8.3
  # State management
  provider: ^6.1.1
  # Navigation
  go_router: ^13.0.0
  # Graphiques
  fl_chart: ^0.67.0
  # Notifications locales
  flutter_local_notifications: ^17.0.0
  # Utilitaires
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  # UI
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/